spring:
  application:
    name: spring-admin-server

server:
  port: 7000

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'