server:
  port : 8081
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID # 防止Cookie衝突，衝突會導致登錄驗證不通過

security:
  oauth2:
    sso:
      login-path: /callback
    client:
      clientId: webclient
      clientSecret: webclient12345678
      user-authorization-uri: http://localhost:8080/oauth/authorize
      access-token-uri: http://localhost:8080/oauth/token

    resource:
      token-info-uri: http://localhost:8080/oauth/check_token

logging.level.org.springframework.security: DEBUG