spring:
  application:
    name: Topic Stream Two input Consumer

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092

      bindings:
        process-in-0:
          destination: greetings1
          contentType: application/json
        process-in-1:
          destination: greetings2
          contentType: application/json

server:
  port: 8007

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
        integration: DEBUG
