spring:
  application:
    name: Stream Functional Sourcer

  cloud:
    stream:
      bindings:
        source-out-0:
          destination: test-source
          binder: kafka

      source: source

      binders:
        kafka:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:9092

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
        integration: DEBUG
        kafka.config: DEBUG

server:
  port: 9999