spring:
  application:
    name: spring-cloud-eureka
  security:
    user:
      name: user
      password: password

server:
  port: 8000

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false