version: '3'
services:
  fluentd:
    build: .
    volumes:
      - ./conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "20001:20001"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.1
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.9.1
    links:
      - "elasticsearch"
    ports:
      - "5602:5601"
