spring:
  application:
    name: spring-cloud-producer

server:
  port: 9000

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/