spring:
  application:
    name: Topic Stream Aggregator

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092

      bindings:
        input:
          destination: greetings1
          contentType: application/json
        output:
          destination: processing
          contentType: application/json

server:
  port: 8002