spring:
  application:
    name: spring-cloud-consumer

  cloud:
    loadbalancer:
      ribbon:
        enable: false # Enable the ribbon, so will use the spring cloud loadbalancer default

server:
  port: 9001

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/

feign:
  hystrix:
    enabled: true