version: '3.7'

services:
  mariadb:
    image: mariadb:10.6.7
    hostname: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${MARIADB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
