---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: springboot-app-prometheus-sa
  namespace: backend
spec:
  hosts:
    - "api.backend.com"
  gateways:
    - istio-system/gateway
  http:
    - match:
        - uri:
            prefix: /springboot-app-prometheus-sa/
      rewrite:
        uri: /
      route:
        - destination:
            host: springboot-app-prometheus-sa
            port:
              number: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-prometheus-sa
  namespace: backend
spec:
  selector:
    app: springboot-app-prometheus-sa
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-prometheus-sa
  namespace: backend
  labels:
    app: springboot-app-prometheus-sa
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8081"
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: springboot-app-prometheus-sa
    spec:
      containers:
        - name: springboot-app-prometheus-sa
          image: org.example/app-standalone:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http
          resources: {}
      restartPolicy: Always
  selector:
    matchLabels:
      app: springboot-app-prometheus-sa
