server:
  port : 8081

security:
  oauth2:
    client:
      clientId: webclient
      clientSecret: webclient12345678

    resource:
      jwt:
        key-value: FEWS_KEY

logging.level.org.springframework.security: DEBUG