server:
  port : 8081

security:
  oauth2:
    client:
      clientId: webclient
      clientSecret: webclient12345678

    resource:
      token-info-uri: /oauth/check_token

logging.level.org.springframework.security: DEBUG