spring:
  application:
    name: spring-cloud-consumer

server:
  port: 9001

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/

security:
  oauth2:
    resource:
      jwt:
        key-value: FEWS_KEY