spring:
  application:
    name: Stream Sourcer

  cloud:
    stream:
      bindings:
        output:
          destination: test-source
          binder: kafka

      binders:
        kafka:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:9092

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
        integration: DEBUG
        kafka.config: DEBUG

server:
  port: 9999