spring:
  profiles:
    active: listener2

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092

      bindings:
        input:
          destination: processing
          contentType: application/json
---
spring:
  application:
    name: Topic Listener
  
  profiles: listener1
  
server:
  port: 8000
  
---
spring:
  application:
    name: Topic Listener
  
  profiles: listener2
  
server:
  port: 8001