spring:
  application:
    name: Topic Listener

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092

      bindings:
        input:
          destination: processing
          contentType: application/json

server:
  port: 8001