server:
  port: 8080

spring:
  application:
    name: demo-spring-mybatis

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: test123456
