server:
  port: 8080

spring:
  application:
    name: demo-spring-mybatis

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: test123456

  sql:
    init:
      schema-locations:
        - classpath:schema.sql

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*Mapper.xml
