server:
  port: 10000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/oauth/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health,info