spring:
  application:
    name: Topic Sender2

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092

      bindings:
        output:
          destination: greetings2
          contentType: application/json
          
server:
  port: 8004