server:
  port: 10000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9001/oauth2/jwks

management:
  endpoints:
    web:
      exposure:
        include: health,info
