server:
  port: 9002

spring:
  zipkin:
    base-url: http://localhost:9411

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/