server:
                  port: 8000

                  spring:
                    application:
                      name: admin-server

                    security:
                      user:
                        name: adminserver
                        password: password